=== dataquest-dev/DSpace/dspace/config/submission-forms.dtd
<!-- DSpace Custom Submit input form definition language -->


 <!ELEMENT input-forms (form-definitions, form-value-pairs, form-complex-definitions) >

 <!ELEMENT form-definitions (form)+ >
 <!ELEMENT form (row)+ >
 <!ELEMENT form-complex-definitions (definition)+ >
 <!ELEMENT row (field|relation-field)+ >
 <!ATTLIST form name NMTOKEN #REQUIRED>

 <!ELEMENT field (dc-schema, dc-element, dc-qualifier?, language?, repeatable?, label, style?, type-bind?, input-type, default-value?, hint, required?, regex?, vocabulary?, visibility?, readonly?, acl?) >
 <!ELEMENT definition (input*) >
 <!ATTLIST definition
        name CDATA #REQUIRED
        >
        
 <!ELEMENT dc-schema (#PCDATA) >
 <!ELEMENT dc-element (#PCDATA) >
 <!ELEMENT dc-qualifier (#PCDATA) >
 <!ELEMENT language (#PCDATA)>
 <!ELEMENT type-bind (#PCDATA) >
 <!-- When you configure special field for the `type-bind` you must update it in the `submit.type-bind.field`
  configuration property like this: `<INPUT_METADATA_FIELD>=><TYPE_BIND_FIELD>` e.g. `dc.language.iso=>edm.type`-->
 <!ATTLIST type-bind field CDATA #IMPLIED >

 <!ELEMENT repeatable (#PCDATA) >
 <!ELEMENT label (#PCDATA) >
 <!ELEMENT style (#PCDATA) >
 <!ELEMENT input-type (#PCDATA)>
 <!ELEMENT default-value (#PCDATA)>

 <!ELEMENT input (#PCDATA) >
 <!ATTLIST input input-type CDATA #REQUIRED >
 <!ATTLIST input name CDATA #REQUIRED >
 <!ATTLIST input label CDATA #IMPLIED >
 <!ATTLIST input regex CDATA #IMPLIED >
 <!ATTLIST input value-pairs-name CDATA #IMPLIED >
 <!ATTLIST input hint CDATA #IMPLIED >
 <!ATTLIST input autocomplete CDATA #IMPLIED >
 <!ATTLIST input placeholder CDATA #IMPLIED >
 <!ATTLIST input id CDATA #IMPLIED >
 <!ATTLIST input class CDATA #IMPLIED >
 <!ATTLIST input readonly CDATA #IMPLIED >
 <!ATTLIST input mapped-to-if-not-default CDATA #IMPLIED >
 <!ATTLIST input value CDATA #IMPLIED >
 <!ATTLIST input required CDATA #IMPLIED >
 <!ATTLIST input default-value CDATA #IMPLIED >

 <!ELEMENT hint (#PCDATA) >
 <!ELEMENT required (#PCDATA)>
 <!ELEMENT name-variants (#PCDATA)>
 <!ELEMENT regex (#PCDATA) >

 <!--
      ACL element for fine-grained access control
      the content should be semicolon separated list of entries in format matching the following regexp:
      policy=(allow|deny),action=(read|write),grantee-type=(user|group),grantee-id=(<UUID>)
 -->
 <!ELEMENT acl (#PCDATA)>

 <!ELEMENT form-value-pairs (value-pairs)* >
 <!ELEMENT value-pairs (pair)+ >

 <!-- ***
        To assign a particular 'value-pairs' list to a particular dropdown 'input-type'
        field, as found on a particular form, put:
        - value-pairs/@value-pairs-name string into
           form/page/field/input-type/@value-pairs-name
        - form/page/field/@DCelement + '_' + form/field/DCqualifier into
           value-pairs/@dc-term
             (e.g. 'language_iso')
  -->
 <!ATTLIST value-pairs value-pairs-name CDATA #REQUIRED
                            dc-term   CDATA #REQUIRED
 >

 <!ELEMENT pair (displayed-value,stored-value) >
 <!ELEMENT displayed-value (#PCDATA)>
 <!ELEMENT stored-value (#PCDATA)>

 <!ATTLIST input-type value-pairs-name CDATA  #IMPLIED>
 <!ATTLIST input-type complex-definition-ref CDATA  #IMPLIED>
 <!ATTLIST input-type autocomplete-custom CDATA  #IMPLIED>

 <!ELEMENT vocabulary (#PCDATA) >

 <!ATTLIST vocabulary closed (true|false) "false">
 <!ATTLIST vocabulary type (xml|authority|suggest) "xml">

 <!ELEMENT visibility (#PCDATA) >

 <!ATTLIST language value-pairs-name CDATA  #IMPLIED>

 <!ELEMENT readonly (#PCDATA) >

<!ELEMENT relationship-type (#PCDATA) >
<!ELEMENT search-configuration (#PCDATA) >
<!ELEMENT filter (#PCDATA) >
<!ELEMENT externalsources (#PCDATA) >
<!ELEMENT relation-field (relationship-type, search-configuration, filter?, repeatable?, name-variants?, label, type-bind?, hint, linked-metadata-field?, externalsources?, required?, regex?, visibility?)>
<!ELEMENT linked-metadata-field (dc-schema, dc-element, dc-qualifier?, input-type)>

=== dataquest-dev/DSpace/dspace/config/vsb/evyuka_form_AUD.xml
<?xml version="1.0"?>
<!DOCTYPE form-definitions SYSTEM "submission-forms.dtd">

<form-definitions>
    <form name="e-vyuka-AUDpageone">
       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>title</dc-element>
           <dc-qualifier></dc-qualifier>
           <label>Název dokumentu</label>
           <input-type>onebox</input-type>
           <hint>Zadejte název dokumentu v jazyce, v němž je napsán. Podnázev oddělte dvojtečkou. Příklad názvu: Matematika: vzorová cvičení</hint>
           <required>Vyplňte pole s názvem dokumentu.</required>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>title</dc-element>
           <dc-qualifier>alternative</dc-qualifier>
           <label>Další název</label>
           <input-type>onebox</input-type>
           <hint>Zadejte další název, např. překlad názvu.</hint>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>contributor</dc-element>
           <dc-qualifier>author</dc-qualifier>
           <repeatable>true</repeatable>
           <label>Autor</label>
           <input-type>name</input-type>
           <hint>Zadejte příjmení a jméno autora/autorů.</hint>
           <required>Vyplňte jméno a příjmení autora</required>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>description</dc-element>
           <dc-qualifier>abstract</dc-qualifier>
           <repeatable>false</repeatable>
           <label>Abstrakt</label>
           <input-type>textarea</input-type>
           <hint>Vložte abstrakt dokumentu.</hint>
           <required></required>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>subject</dc-element>
           <dc-qualifier></dc-qualifier>
           <repeatable>true</repeatable>
           <label>Klíčová slova</label>
           <input-type>onebox</input-type>
           <hint>Vložte odpovídající klíčová slova nebo fráze. Každé klíčové slovo nebo frázi do samostatného pole.</hint>
           <required></required>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>language</dc-element>
           <dc-qualifier>iso</dc-qualifier>
           <repeatable>false</repeatable>
           <label>Jazyk</label>
           <input-type value-pairs-name="language_evyuka">dropdown</input-type>
           <hint>Vyberte jazyk, ve kterém je dokument napsán.</hint>
           <required>Vyberte jazyk.</required>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>date</dc-element>
           <dc-qualifier>issued</dc-qualifier>
           <repeatable>false</repeatable>
           <label>Rok vydání</label>
           <input-type>onebox</input-type>
           <hint>Zadejte rok vydání (vytvoření dokumentu). Uveďte rok ve formátu RRRR.</hint>
         </field>
       </row>
    </form>

    <form name="e-vyuka-AUDpagetwo">
       <row>
         <field>
           <dc-schema>evyuka</dc-schema>
           <dc-element>subject</dc-element>
           <dc-qualifier>version</dc-qualifier>
           <repeatable>true</repeatable>
           <label>Kód verze předmětu</label>
           <input-type value-pairs-name="vp_subject-version_AUD">dropdown</input-type>
           <hint>Vyberte kódy všech verzí předmětu, kterých se dokument týká. Dokument bude dostupný pouze vyjmenovaným verzím předmětů.</hint>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>evyuka</dc-schema>
           <dc-element>subject</dc-element>
           <dc-qualifier></dc-qualifier>
           <repeatable>true</repeatable>
           <label>Kód předmětu</label>
           <input-type value-pairs-name="vp_subject_AUD">dropdown</input-type>
           <hint>Vyberte kódy všech předmětů, kterých se dokument týká. Dokument bude rovněž společný pro všechny verze těchto předmětů.</hint>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>evyuka</dc-schema>
           <dc-element>discipline</dc-element>
           <dc-qualifier></dc-qualifier>
           <repeatable>true</repeatable>
           <label>Kód studijního oboru</label>
           <input-type value-pairs-name="vp_branch_AUD">dropdown</input-type>
           <hint>Vyberte kódy všech studijních oborů, kterých se dokument týká.</hint>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>evyuka</dc-schema>
           <dc-element>programme</dc-element>
           <dc-qualifier></dc-qualifier>
           <repeatable>true</repeatable>
           <label>Kód studijního programu</label>
           <input-type value-pairs-name="vp_program_AUD">dropdown</input-type>
           <hint>Vyberte kódy všech studijních programů, kterých se dokument týká.</hint>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>rights</dc-element>
           <dc-qualifier>access</dc-qualifier>
           <repeatable>false</repeatable>
           <label>Přístupová práva k souboru</label>
           <input-type value-pairs-name="document_access_rights">dropdown</input-type>
           <hint>Vyberte přístupová práva k souboru s textem dokumentu.</hint>
           <required></required>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>description</dc-element>
           <dc-qualifier>provenance</dc-qualifier>
           <repeatable>true</repeatable>
           <label>Poznámka pro schvalujícího pracovníka knihovny</label>
           <input-type>textarea</input-type>
           <hint>Uveďte, pokud potřebujete nastavit něco, na co nemáte dostatečná oprávnění.</hint>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>description</dc-element>
           <dc-qualifier>placeofpublication</dc-qualifier>
           <repeatable>false</repeatable>
           <label>Místo vydání</label>
           <input-type>onebox</input-type>
           <hint>Zadejte místo vydání.</hint>
         </field>
       </row>
    </form>

    <form name="e-vyuka-AUDpagethree">
       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>publisher</dc-element>
           <dc-qualifier></dc-qualifier>
           <repeatable>false</repeatable>
           <label>Nakladatel</label>
           <input-type>onebox</input-type>
           <hint>Zadejte nakladatele.</hint>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>relation</dc-element>
           <dc-qualifier>ispartofseries</dc-qualifier>
           <repeatable>false</repeatable>
           <label>Název časopisu nebo edice</label>
           <input-type>onebox</input-type>
           <hint></hint>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>identifier</dc-element>
           <dc-qualifier></dc-qualifier>
           <repeatable>true</repeatable>
           <label>Identifikátory</label>
           <input-type value-pairs-name="common_identifiers">qualdrop_value</input-type>
           <hint>Vyberte a doplňte identifikátor dokumentu, pokud je dokumentu přidělen.</hint>
           <required></required>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>type</dc-element>
           <dc-qualifier></dc-qualifier>
           <repeatable>true</repeatable>
           <label>Typ dokumentu</label>
           <input-type value-pairs-name="types_evyuka">dropdown</input-type>
           <hint>Vyberte typ dokumentu. (Vyberte jednu, popřípadě více možností.)</hint>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>relation</dc-element>
           <dc-qualifier>projectid</dc-qualifier>
           <repeatable>false</repeatable>
           <label>Číslo projektu</label>
           <input-type>onebox</input-type>
           <hint>Zadejte číslo projektu. Např. CZ.02.2.69/0.0/0.0/16_015/0002338</hint>
         </field>
       </row>

       <row>
         <field>
           <dc-schema>dc</dc-schema>
           <dc-element>relation</dc-element>
           <dc-qualifier>projectname</dc-qualifier>
           <repeatable>false</repeatable>
           <label>Název projektu</label>
           <input-type>onebox</input-type>
           <hint>Zadejte název projektu. Např. Publish and Flourish: Podpora publikační činnosti doktorandů a školitelů</hint>
         </field>
       </row>
    </form>

</form-definitions>
